-- ============================================
-- PRONTPET - DATABASE INITIALIZATION
-- MySQL
-- ============================================

CREATE DATABASE IF NOT EXISTS prontpet;

USE prontpet;

CREATE TABLE IF NOT EXISTS TB_OWNER (
    ID BIGINT AUTO_INCREMENT,
    NAME VARCHAR(255),
    CPF VARCHAR(255),
    EMAIL VARCHAR(255),
    PHONE VARCHAR(255),
    PASSWORD VARCHAR(255),

    CONSTRAINT PK_TB_OWNER PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS TB_CLINIC (
    ID BIGINT AUTO_INCREMENT,
    NAME VARCHAR(255),
    CNPJ VARCHAR(255),
    ADDRESS VARCHAR(255),
    PHONE VARCHAR(255),
    OPENING_HOURS TIME,
    CLOSING_HOURS TIME,

    CONSTRAINT PK_TB_CLINIC PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS TB_PET (
    ID BIGINT AUTO_INCREMENT,
    NAME VARCHAR(255),
    SPECIES VARCHAR(255),
    BREED VARCHAR(255),
    BIRTH_DATE DATE,
    WEIGHT DECIMAL(10,2),
    SEX VARCHAR(50),
    OWNER_ID BIGINT,

    CONSTRAINT PK_TB_PET PRIMARY KEY (ID),

    CONSTRAINT FK_PET_OWNER
        FOREIGN KEY (OWNER_ID)
        REFERENCES TB_OWNER(ID)
);

CREATE TABLE IF NOT EXISTS TB_APPOINTMENT (
    ID BIGINT AUTO_INCREMENT,
    SPECIALITY VARCHAR(255),
    SYMPTOMS VARCHAR(255),
    DIGNOSIS VARCHAR(255),
    OBSERVATIONS VARCHAR(255),
    APPOINTMENT_DATE DATETIME,
    UPDATED_WEIGHT DECIMAL(10,2),
    CLINIC_ID BIGINT,
    PET_ID BIGINT,

    CONSTRAINT PK_TB_APPOINTMENT PRIMARY KEY (ID),

    CONSTRAINT FK_APPOINTMENT_CLINIC
        FOREIGN KEY (CLINIC_ID)
        REFERENCES TB_CLINIC(ID),

    CONSTRAINT FK_APPOINTMENT_PET
        FOREIGN KEY (PET_ID)
        REFERENCES TB_PET(ID)
);
